### ISSUE TITLE
Did not find request headers from Firefox

### ISSUE THREAD

**Issue by hanglearning** [apastel/ytmusic-deleter#11]
Sorry for a dumb question... but when I started ytmusic-deleter, I did not see my Firefox popped up and gave me any header. I have updated my Firefox to the newest version and also tried having it opened. Could you give any directions? I've tried both on MacOS and Ubuntu 20.04. 

Thanks!

**Comment by apastel** [comment]
Running ytmusic-deleter will not automatically open Firefox and give you your request headers (although that would be cool if it did). You must follow the instructions for copying them to your clipboard provided by `ytmusicapi` here under "Copy authentication headers" https://ytmusicapi.readthedocs.io/en/latest/setup.html
