### ISSUE TITLE
For some reason *nothing* gets deleted.

### ISSUE THREAD

**Issue by DaleHennessey** [apastel/ytmusic-deleter#2]
**UPDATE**:  This appears to have a been a problem with how I was constructing the auth_headers.json file.  I didn't get any permission errors, but I also couldn't actually delete anything.  All fixed now, though! :)

I have this installed and it _does_ run.  
I'm seeing what appears to be the most recent change (pull master on 15 Sep at 0830EST) of showing progress bar for the operations to delete -- *all* of the operations to delete; however, it seems to operate on zero items, and I cannot figure out why.  
Any tips/tricks for something that I might be missing?

**Final few logs of installation to show dep vesrions:**

```
Installing collected packages: ytmusicapi, ytmusic-deleter
  Running setup.py install for ytmusic-deleter ... done
Successfully installed ytmusic-deleter-0.1 ytmusicapi-0.9.2
WARNING: You are using pip version 19.2.2, however version 20.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Sample output:**

```
~\Downloads\ytmusic-deleter [master ≡ +0 ~1 -0 !]> ytmusic-deleter remove-library
[2020-09-15 08:28:37] Retrieving all library albums...
[2020-09-15 08:28:38] Retrieving all singles...
[2020-09-15 08:28:38] Removed 0 out of 0 albums from your library.

Albums Processed 100%|████████████████████████████████████████████████████████████████| 0/0 [00:00<00:00, 0.00 albums/s]~\Downloads\ytmusic-deleter [master ≡ +0 ~1 -0 !]>            
```

**Comment by apastel** [comment]
Hmm. If you go into YT Music and add some random albums to your library and then run it again, do you get the same result?

Only way I can partially replicate this is if my library has only one "single" (i.e. a song that is not part of an album). The single won't get retrieved unless there is more than one single in the library.

If you want to pull changes again, I just made a commit that prints out how many albums it retrieved from your library before the removal begins. But I'm guessing it will just say 0.

**Comment by DaleHennessey** [comment]
Thanks for the reply!  I'll give it a shot in the next day or two and see what shows up in the console.  

The only stuff in my YouTube Music library right now is the "transfer" from Google Play Music and it was a sh*t-show of bad tags and duplicates which I'm trying to get rid of. :)

**Comment by apastel** [comment]
Heh, that shit-show is why I created this, and the fact that it is, in fact, a shit-show of bad metadata is what's causing most of the failures using `ytmusicapi`. :disappointed:

**Comment by DaleHennessey** [comment]
I'm so disillusioned by Google these days.  Their IoT with Google Assistant and Nest stupidity made me burn that bridge.  Thank YOU, btw, for writing this.  My alternative before finding your repo mentioned on reddit was going to be to write a javascript function to "press all the delete buttons" for me on the album and song pages.

... And I despise Javascript! ;)

**Comment by apastel** [comment]
I tried one of those javascript solutions that someone posted to Reddit, but it just didn't work for me and I saw others saying the same. So that's what led me to write a back-end solution. It works slightly better (when it works :stuck_out_tongue: )

**Comment by DaleHennessey** [comment]
Woohoo! I figured it out!  I was constructing my headers_auth.json file incorrectly.  This should teach me to never "gloss over" important bits and read them a bit more thoroughly.  Thanks for all your help, @apastel!

**Comment by apastel** [comment]
Oh, good to hear!
I had the choice of having the user paste their cookie into the existing headers_auth.json, or just having the program prompt the user for their cookie to paste into stdin the first time they run the program and have headers_auth.json be generated automatically. I thought the former was the better option but maybe it's not.
Just curious, how did your headers_auth.json file look when it was incorrect? Were you missing any of the other properties? Or was your cookie copy/pasted wrong?

**Comment by DaleHennessey** [comment]
I suspect that someone else besides the cookie was missing or wrong -- even though I didn't drill down to confirm that.  When I copied the whole block over from my browser and then trimmed the duplicates out it started working again.  Your process (and the link to the ytmusic api instructions) were good -- I just rushed and blew it. :)
