### ISSUE TITLE
Error Message During Install

### ISSUE THREAD

**Issue by Tvandi** [apastel/ytmusic-deleter#68]
I really want to use this app but I'm getting the following error:
![Error message](https://github.com/user-attachments/assets/e5359e00-259c-4f96-9fc0-9813f26d4071)

Any idea what I'm doing wrong? Thanks!

**Comment by apastel** [comment]
It sounds like the installer does not have permission to install to your `C:\Program Files (x86)` directory, if I had to guess. That is typically a "system" folder, which means the computer has to ask you to elevate to admin privileges before it runs the installer. If you don't have admin privileges on the computer, it might not even let you do that.

Do you see a prompt like this when you run the installer?
![image](https://github.com/user-attachments/assets/4360b0c1-262b-4444-a8f4-d73605b87e50)

**Comment by Tvandi** [comment]
Hello, Yes, that's the prompt I'm getting.

**Comment by apastel** [comment]
And did you click "Yes"?

**Comment by Tvandi** [comment]
Yes sir.

**Comment by apastel** [comment]
Hmm, maybe it isn't a permission issue then. It could be your anti-virus blocking the creation of an .exe file, not really sure. What happens if you click "Ignore" to skip the file? I know the app won't work without it, but I'm curious if that same error shows up for other files or if it's just the .exe file. If it's just the .exe file, that tells me it might be an anti-virus issue.

**Comment by Tvandi** [comment]
It's probably the anti-virus, I'll run some tests. Thanks for your help and
I'll definitely leave a donation once I get this thing figured out.

**Comment by apastel** [comment]
Worst-case scenario you can install the non-user-interface version if you're comfortable following some instructions to use it on the command line: https://github.com/apastel/ytmusic-deleter/blob/main/ytmusic_deleter/README.md

**Comment by apastel** [comment]
Any luck?

**Comment by apastel** [comment]
Just checking again if you had any luck installing the app. Will close this issue if I don't hear back in a few days.

**Comment by Tvandi** [comment]
Hello Alex, thanks for checking in. I gave up on trying to make it work but have shared the link with colleagues who asked about it. Have a great day.
