### ISSUE TITLE
Random artist stuck in library that won't disappear

### ISSUE THREAD

**Issue by ArreglarYTM** [apastel/ytmusic-deleter#78]
I have a problem related to one artist that had a song previously, but currently no, it seems to be related a bug into YTM, also I make like to the song, but doesn´t dessapear from my artists library. ¿Could you implement that feature on the app?, ¿Google API support this option?
Thank you in advance.
Cheers.
![Captura de pantalla 2024-10-16 195933](https://github.com/user-attachments/assets/92afd65e-fc0c-4cc1-80f3-9210d0e072ee)
![Captura de pantalla 2024-10-16 195948](https://github.com/user-attachments/assets/0b7c0860-17b9-429f-9a41-3fa3a8a5538e)

**Comment by apastel** [comment]
If you already tried the "Delete All" button on my app and it says that it deleted everything, then unfortunately there's nothing more that my app can do. YouTube Music has bugs sometimes, and this looks like a bug. I would recommend trying the "Delete All" button again, or at least the "Unlike All" button to make sure there is not a reference to the song that is lingering around somewhere, since you mentioned that you "made like to the song".

**Comment by ArreglarYTM** [comment]
I have tried to talk to Youtube support and I have been waiting for a solution for 3 months. I had Youtube Premium but I decided not to renew it after this problem...

I know the URL of the song that I liked a few months ago and that is no longer available but I can't delete it...

https://music.youtube.com/watch?v=V07Mo0LAfLw

**Comment by apastel** [comment]
I see. Yeah that is definitely a bug with YouTube Music. There is some kind of lingering reference to the song. There might be a clever way to experiment with different functions of the [ytmusicapi](https://ytmusicapi.readthedocs.io/en/stable/index.html) and find a way to get a reference to it and remove it, but that's basically what my tool already does.

**Comment by ArreglarYTM** [comment]
Do you think I have nothing to do? Could you please try to make your tool able to read hidden songs so that they can be removed? The problem is that I can't unlike a song that is no longer available but it is still listed...

If I want to use Youtube Music again and regain trust I need to fix the problem and prevent it from becoming bigger in the future..

Thanks for your messages

**Comment by apastel** [comment]
Did you already try using the "Delete All" button in my YTMusic Deleter app?

**Comment by ArreglarYTM** [comment]
I've already tried deleting everything with your tool and it deleted everything except for this unavailable song that appears from the artist FlowGPT. Tomorrow I'll call YouTube support again, but from what I've been told, they've already escalated it several times and they don't know when it's going to be fixed. They also don't assure me that it can be fixed. I don't know if they really don't have a clue...

When I talk to YouTube support I don't talk to the devs. They pass notes and the feeling is that you're stuck after 3 months.

**Comment by apastel** [comment]
Yep, that's pretty much the experience across the board with Google. I have another bug I've been trying to get them to fix for years with their password manager in Android apps. The customer support doesn't fully understand the problem and it's too low priority for them to fix apparently. It's part of the reason I had to make this app in the first place -- to fill a gap that the software developers completely overlooked or don't care to support. It's unfortunate. 

The only other way I could help you if you are truly desperate, is that you can send me your `oauth.json` file. That is the file that should be in your %APP_DATA%/Roaming/YTMusic_Deleter directory, where %APP_DATA% is usually C:\Users\<username>\AppData. If you send me that file, I can experiment with using the API to try to delete the FlowGPT artist. You just have to be aware that you are essentially sending me the keys to your YouTube Music library. I will of course respect it and only use it to try to delete this one thing. But that's completely up to you if you are comfortable doing that. If you choose to do it, you can send it to my email address alex.r.pastel@gmail.com

**Comment by ArreglarYTM** [comment]
Hi, any news regarding the problem I reported a few weeks ago? I've seen that the same thing is happening to other people... Songs that had a like and are no longer available are left in limbo because they can't be removed...

**Comment by apastel** [comment]
No, my last messages pretty much sum it up. It's a bug in YTMusic. It's a hard problem to replicate so I can't develop a fix for it without testing it on my end first. My tool deletes your whole library. The thing that is remaining in your library is not a song, it's some kind of hanging reference that cannot be retrieved with the API that my tool uses. Sorry I can't be of more help.
