### ISSUE TITLE
Unable to sign in (400 Bad Request error)

### ISSUE THREAD

**Issue by apastel** [apastel/ytmusic-deleter#85]
At some point in the last few days, Google changed something that broke the OAuth sign-in API employed by [ytmusicapi](https://github.com/sigma67/ytmusicapi/issues/676), which is the library that this app depends on.

In other words, you can't sign into YTMusic Deleter right now because its dependency is not working. You can see the issue being tracked here: https://github.com/sigma67/ytmusicapi/issues/676

This type of thing happens from time to time. Google changes something that breaks ytmusicapi (it's an unofficial API), and it takes a few days for the open-source community to catch up and fix it.

Once that happens, I will update this app immediately with the fix and release a new version.

NOTE: Not everyone is experiencing the issue, but it seems relatively widespread. You may be one of the lucky ones whom it's still working for. It's not working for me, I can say that much. Only the old-school method of authentication is working for me (pasting request headers from Firefox), but I removed that option from YTMusic Deleter some time ago.

![image](https://github.com/user-attachments/assets/7e4c3521-49ea-4731-9806-a0c8f9f3dbb2)

**Comment by alohith** [comment]
I'm having this issue. following the link in both the CLI and Windows exe, leads to a 'successful' auth, but your the deleter says it's failed in login

**Comment by apastel** [comment]
> I'm having this issue. following the link in both the CLI and Windows exe, leads to a 'successful' auth, but your the deleter says it's failed in login

Yeah unfortunately Google's change is being rolled out to everybody it seems. They may be doing away with OAuth completely which would suck. It means we have to go back to the old method of authentication which is pasting in a cookie from your browser's network toolbar. It's doable but just a lot less user-friendly. I'll have to spend some time bringing that old code back, and probably what I'll do is keep both options around in case OAuth is re-enabled again by Google later.

Just as a heads-up, this affects every application out there that attempts to sign you into YouTube or YouTube Music, so you'll see a lot of chatter about it all across GitHub right now:

https://github.com/KoljaWindeler/ytube_music_player/issues/367#issuecomment-2472397147
https://github.com/music-assistant/hass-music-assistant/issues/3138#issuecomment-2471316657
https://github.com/yt-dlp/yt-dlp/issues/11462#issuecomment-2471087887
